### ISSUE TITLE
[feature-request] Allow setting up multiple npm tokens

### ISSUE THREAD

**Issue by arthurw1** [seek-oss/private-npm-buildkite-plugin#6]
We have a use case that requires us to pull deps from multiple private npm repositories, each requiring a unique npm token. Will it make sense to request for this feature in this plugin?

Thanks!

**Comment by arthurw1** [comment]
I'd be open to work on this PR, but will need some guidance on how to go about it!

**Comment by 72636c** [comment]
Hey @arthurw1! I think the first step is to determine how the config will look like.

Do you have any ideas here? e.g.

```yaml
- seek-oss/private-npm#v1.2.0:
    registry:
      - path: //registry.npmjs.org/
        env: MY_ENV_VAR
      - path: //myprivatenpm.com/
        file: my_token_file
```

**Comment by arthurw1** [comment]
Hi @72636c 

I was thinking of the following. Similar to your suggestion but without the `registry` nesting:

```
plugins:
  - seek-oss/private-npm#v1.2.0:
      - env: "TOKEN_1"
        registry: //myprivatenpm1.com/
      - env: "TOKEN_2"
        registry: //myprivatenpm2.com/
```

Do we need to accommodate for cases where `file` or `token` fields are provided instead?

**Comment by 72636c** [comment]
LGTM! Let's start out with `env` support, and we can add the others later if there's a need.

There's an example of parsing out a string list in the Docker ECR Cache plugin: https://github.com/seek-oss/docker-ecr-cache-buildkite-plugin/blob/d2a4b4763f2fe9c01a79eab10633bddcbc8e4f4c/hooks/lib/stdlib.bash#L23-L26. The code here may be slightly more involved since we'd be accessing nested names like `"BUILDKITE_PLUGIN_PRIVATE_NPM_${INDEX}_ENV"` and `"BUILDKITE_PLUGIN_PRIVATE_NPM_${INDEX}_REGISTRY"`.

**Comment by arthurw1** [comment]
I see. Will look into it!

**Comment by arthurw1** [comment]
@72636c 

I ended up with a schema that is similar to your initial suggestion:
```yaml
- seek-oss/private-npm#v1.2.0:
    multi-registries:
      - path: //registry.npmjs.org/
        env: MY_ENV_VAR
      - path: //myprivatenpm.com/
        file: my_token_file
```

The feature is added and seems to be working when running `pre-command` locally. But I'd also like to test if my `plugin.yml` is configured correctly and if the variables are mapped as expected -- what is the best way to do this?
